version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "daily"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
